### ISSUE TITLE
安装文档配置启动报错

### ISSUE THREAD

**Issue by defp** [X-Profiler/all-in-one#3]
https://www.yuque.com/hyj1991/easy-monitor/deployment 

```
ez-monitor  | 2024-01-08 08:48:07,623 INFO 4659 [egg:loader] Use middleware: i18n
ez-monitor  | 2024-01-08 08:48:07,623 INFO 4659 [egg:loader] Loaded middleware from ["/usr/src/app/node_modules/.store/egg-session@3.3.0/node_modules/egg-session/app/middleware","/usr/src/app/node_modules/.store/egg-security@3.2.0/node_modules/egg-security/app/middleware","/usr/src/app/node_modules/.store/egg-jsonp@2.0.0/node_modules/egg-jsonp/app/middleware","/usr/src/app/node_modules/.store/egg-onerror@2.2.0/node_modules/egg-onerror/app/middleware","/usr/src/app/node_modules/.store/egg-i18n@2.1.1/node_modules/egg-i18n/app/middleware","/usr/src/app/node_modules/.store/egg-watcher@3.1.1/node_modules/egg-watcher/app/middleware","/usr/src/app/node_modules/.store/egg-schedule@4.0.0/node_modules/egg-schedule/app/middleware","/usr/src/app/node_modules/.store/egg-multipart@3.3.0/node_modules/egg-multipart/app/middleware","/usr/src/app/node_modules/.store/egg-logrotator@3.1.0/node_modules/egg-logrotator/app/middleware","/usr/src/app/node_modules/.store/egg-static@2.3.1/node_modules/egg-static/app/middleware","/usr/src/app/node_modules/.store/egg-view@2.1.4/node_modules/egg-view/app/middleware","/usr/src/app/node_modules/.store/egg-mysql@3.4.0/node_modules/egg-mysql/app/middleware","/usr/src/app/node_modules/.store/egg-redis@2.5.0/node_modules/egg-redis/app/middleware","/usr/src/app/node_modules/.store/egg-view-ejs@2.0.1/node_modules/egg-view-ejs/app/middleware","/usr/src/app/node_modules/.store/egg-remote-config@1.0.1/node_modules/egg-remote-config/app/middleware","/usr/src/app/node_modules/.store/@xprofiler+manager@1.0.1/node_modules/@xprofiler/manager/lib/plugin/egg-xprofiler-mailer/app/middleware","/usr/src/app/node_modules/.store/@xprofiler+manager@1.0.1/node_modules/@xprofiler/manager/lib/plugin/egg-xprofiler-dingtalk/app/middleware","/usr/src/app/node_modules/.store/@xprofiler+manager@1.0.1/node_modules/@xprofiler/manager/lib/plugin/egg-xprofiler-qywx/app/middleware","/usr/src/app/node_modules/.store/@xprofiler+manager@1.0.1/node_modules/@xprofiler/manager/lib/plugin/egg-xprofiler-feishu/app/middleware","/usr/src/app/node_modules/.store/egg-xtransit@2.0.0/node_modules/egg-xtransit/app/middleware","/usr/src/app/node_modules/.store/egg@2.37.0/node_modules/egg/app/middleware","/usr/src/app/node_modules/.store/@xprofiler+manager@1.0.1/node_modules/@xprofiler/manager/app/middleware","/usr/src/app/app/middleware"]
ez-monitor  | 2024-01-08 08:48:07,624 INFO 4659 [egg:loader] Controller loaded: /usr/src/app/app/controller
ez-monitor  | 2024-01-08 08:48:07,627 INFO 4649 [egg:core:ready_stat] end ready task /usr/src/app/node_modules/.store/egg-watcher@3.1.1/node_modules/egg-watcher/lib/init.js:15:14, remain ["/usr/src/app/node_modules/.store/egg-mysql@3.4.0/node_modules/egg-mysql/lib/mysql.js:14:7","/usr/src/app/node_modules/.store/egg-mysql@3.4.0/node_modules/egg-mysql/lib/mysql.js:14:7"]
ez-monitor  | 2024-01-08 08:48:07,627 INFO 4649 [app_worker] receive signal SIGTERM, exiting with code:0
ez-monitor  | 2024-01-08 08:48:07,628 INFO 4649 [app_worker] beforeExit success
ez-monitor  | 2024-01-08 08:48:07,629 INFO 4649 [app_worker] exit with code:0
ez-monitor  | 2024-01-08 08:48:07,629 INFO 4659 [egg:loader] Controller loaded: /usr/src/app/node_modules/.store/@xprofiler+manager@1.0.1/node_modules/@xprofiler/manager/app/controller
ez-monitor  | [2024-01-08 08:48:07.636] [cfork:master:4575] worker:4649 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
ez-monitor  | 2024-01-08 08:48:07,637 INFO 4659 [egg:core] dump config after load, 5ms
ez-monitor  | [2024-01-08 08:48:07.638] [cfork:master:4575] new worker:4691 fork (state: none)
ez-monitor  | [2024-01-08 08:48:07.638] [cfork:master:4575] worker:4649 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
ez-monitor  | 2024-01-08 08:48:07,638 INFO 4575 [master] app_worker#1:4649 disconnect, suicide: false, state: disconnected, current workers: ["1","2","3","4"]
ez-monitor  | [2024-01-08 08:48:07.641] [cfork:master:4575] new worker:4696 fork (state: none)
ez-monitor  | [2024-01-08 08:48:07.641] [cfork:master:4575] worker:4649 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false)
ez-monitor  | 2024-01-08 08:48:07,641 INFO 4575 [master] app_worker#1:4649 disconnect, suicide: false, state: disconnected, current workers: ["1","2","3","4","5"]
ez-monitor  | [2024-01-08 08:48:07.646] [cfork:master:4575] new worker:4697 fork (state: none)
ez-monitor  | [2024-01-08 08:48:07.647] [cfork:master:4575] worker:4649 exit (code: 0, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
ez-monitor  | 2024-01-08 08:48:07,648 ERROR 4575 nodejs.AppWorkerDiedError: [master] app_worker#1:4649 died (code: undefined, signal: null, suicide: false, state: dead), current workers: [4649,4659,4666,4691,4696,4697]
ez-monitor  |     at Master.onAppExit (/usr/src/app/node_modules/.store/egg-cluster@2.2.1/node_modules/egg-cluster/lib/master.js:410:21)
ez-monitor  |     at Master.emit (node:events:517:28)
ez-monitor  |     at Messenger.sendToMaster (/usr/src/app/node_modules/.store/egg-cluster@2.2.1/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
ez-monitor  |     at Messenger.send (/usr/src/app/node_modules/.store/egg-cluster@2.2.1/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
ez-monitor  |     at EventEmitter.<anonymous> (/usr/src/app/node_modules/.store/egg-cluster@2.2.1/node_modules/egg-cluster/lib/utils/mode/impl/process/app.js:114:22)
ez-monitor  |     at EventEmitter.emit (node:events:529:35)
ez-monitor  |     at ChildProcess.<anonymous> (node:internal/cluster/primary:188:13)
ez-monitor  |     at Object.onceWrapper (node:events:632:26)
ez-monitor  |     at ChildProcess.emit (node:events:517:28)
ez-monitor  |     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
ez-monitor  | name: "AppWorkerDiedError"
ez-monitor  | pid: 4575
ez-monitor  | hostname: f0bf30f42d0d
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#1:4649 disconnect, suicide: false, state: disconnected, current workers: ["1","2","3","4","5","6"]
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#4:4691 start, state: none, current workers: ["1","2","3","4","5","6"]
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#4:4691 start, state: none, current workers: ["1","2","3","4","5","6"]
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#4:4691 start, state: none, current workers: ["1","2","3","4","5","6"]
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#5:4696 start, state: none, current workers: ["1","2","3","4","5","6"]
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#5:4696 start, state: none, current workers: ["1","2","3","4","5","6"]
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#5:4696 start, state: none, current workers: ["1","2","3","4","5","6"]
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#6:4697 start, state: none, current workers: ["1","2","3","4","5","6"]
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#6:4697 start, state: none, current workers: ["1","2","3","4","5","6"]
ez-monitor  | 2024-01-08 08:48:07,646 INFO 4575 [master] app_worker#6:4697 start, state: none, current workers: ["1","2","3","4","5","6"]
ez-monitor  | [2024-01-08 08:48:07.649] [cfork:master:4575] worker:4649 exit (code: 0, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
ez-monitor  | TypeError: Cannot read properties of undefined (reading 'isDevReload')
ez-monitor  |     at Master.onAppExit (/usr/src/app/node_modules/.store/egg-cluster@2.2.1/node_modules/egg-cluster/lib/master.js:396:17)
ez-monitor  |     at Master.emit (node:events:517:28)
ez-monitor  |     at Messenger.sendToMaster (/usr/src/app/node_modules/.store/egg-cluster@2.2.1/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
ez-monitor  |     at Messenger.send (/usr/src/app/node_modules/.store/egg-cluster@2.2.1/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
ez-monitor  |     at EventEmitter.<anonymous> (/usr/src/app/node_modules/.store/egg-cluster@2.2.1/node_modules/egg-cluster/lib/utils/mode/impl/process/app.js:114:22)
ez-monitor  |     at EventEmitter.emit (node:events:529:35)
ez-monitor  |     at ChildProcess.<anonymous> (node:internal/cluster/primary:188:13)
ez-monitor  |     at Object.onceWrapper (node:events:632:26)
ez-monitor  |     at ChildProcess.emit (node:events:517:28)
ez-monitor  |     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
ez-monitor  | 2024-01-08 08:48:07,654 ERROR 4575 [master] exit with code:1
ez-monitor  | 2024-01-08 08:48:07,654 ERROR 4575 [master] exit with code:1
ez-monitor  | 2024-01-08 08:48:07,654 ERROR 4575 [master] exit with code:1
ez-monitor  | 2024-01-08 08:48:07,666 ERROR 4666 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
```

有个报错

ez-monitor  | TypeError: Cannot read properties of undefined (reading 'isDevReload')

是什么没有配置吗

**Comment by hyj1991** [comment]
你贴的错误日志里面没有有效信息，建议先看下前置技能需求对 egg 框架有一定了解

**Comment by defp** [comment]
安装文档用docker的方式, 改了数据库配置

docker-compose.yaml
```
version: "3"
services:
  redis:
    image: redis:7.2.3
    restart: always
    container_name: redis
    # ports:
    #   - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./data:/data
    command: redis-server --protected-mode no
    networks:
      - internal

  mysql:
    image: mysql:8.0.33-debian
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: "KC8yeECUheY"
      MYSQL_ROOT_PASSWORD: "KC8yeECUheY"
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Shanghai
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - 3306
    volumes:
      - "./db-data:/var/lib/mysql"
    networks:
      - internal
  ez-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ez-monitor
    restart: always
    ports:
      - "9190:9190"
      - "8443:8443"
      - "8543:8543"
    volumes:
      - ./docker.config.prod.js:/usr/src/app/config/config.prod.js
    networks:
      - internal
    depends_on:
      - mysql
      - redis

networks:
  internal:
    driver: bridge
```

**Comment by defp** [comment]
文档说的 sql 是需要自己手动导入吗?

**Comment by defp** [comment]
可能是sql 的问题, docker 启动的时候是不是没有初始化这个功能?

**Comment by hyj1991** [comment]
> 文档说的 sql 是需要自己手动导入吗?

是的，文档中写了 sql 要手动导入
